
# MediaWiki Action API
<chauthors>Noam Himmelrath, Jacopo Gambato</chauthors>
<br><br>


## Provided services/data

* *What data/service is provided by the API?*
To access *Wikipedia*, *MediaWiki* provides the MediaWiki Action API.

The API can be used for multiple things, such as accessing wiki features, interacting with a wiki and obtaining meta-information about wikis and public users. Additionally, the web service can provide access data and post changes of *Wikipedia*-webpages.


## Prerequesites
* *What are the prerequisites to access the API (authentication)? *

No pre-registration is required to access the API. However, for certain actions, such as very large queries, a registration is required. Moreover, while there is no hard and fast limit on read requests, the system administrators heavily recommend limiting the request rate to secure the stability of the side. It is also best practice to set a descriptive User Agent header. 



## Simple API call
* *What does a simple API call look like?*

As mentioned, the API can be used to communicate with Wikipedia for a variety of actions. As it is most likely for social scientist to extract information rather than post changes to a Wikipedia page, we focus here on obtaining from Wikipedia the information we need. 

We include a basic API call to obtain information about the Albert Einstein Wikipedia page

`https://en.wikipedia.org/w/api.php?action=query&format=json&prop=info&titles=Albert%20Einstein`

to be plugged into the search bar of a browser to obtain the basic information on the page.

Notice that the first line is common for all calls of the API, while the second line relates to the specific action you are trying to perform.

## API access
* *How can we access the API from R (httr + other packages)?* 

The most common tool is `WikipediR`, a wrapper around the Wikipedia API. It allows `R` to access information and "directions" for the relevant page or pages of Wikipedia and the content or metadata therein. Importantly, the wrapper only allows to gather information, which implies that the instrument needs to be accompanied by other packages such as `rvest` for scraping and `XML` or `jsonlite` for parsing.

We report here the code to obtain the same information as in the previous example through `R`:

```{r echo=TRUE}
WikipediR::page_info(
    language = "en", 
    project = "wikipedia", 
    page = "Albert Einstein", 
    properties = "url")
```

## Social science examples
* *Are there social science research examples using the API?*

Some papers using Wikipedia-information rely on the API to access the data. These papers cover a wide range of social and economical sciences. Political science papers are, for example, concerned with political elections, more specifically election prediction [@margolin2016wiki; @salem2021wikipedia]. Other papers use the data accessed through the API to analyze media coverage of the COVID-19 pandemic [@gozzi2020collective] or the interplay between online information and investment markets [@elbahrawy2019wikipedia].




