
# Introduction
The project *APIs for Social Scientists: A Review* is an outcome of the seminar *Computational Social Science* (CSS) taught at the University of Mannheim. While teaching the seminar we had trouble finding short reviews of APIs with quick R-code examples. Fortunately, almost everyone participating in the seminar was motivated enough to write a quick API review. The current document is available in PDF on [OSF](link) and as [HTML](github-link). Hopefully, our ressource will be helpful future students that start to dive into CSS.

Below we review different data- and service-APIs that may be useful to social scientists. The chapters always include a simple R code example as well as references to social science research that has relied on them. The idea is to provide short reviews of max. 10 pages for the corresponding API with code to get you started. Each chapter follows a systematic set of questions: 

* What data/service is provided by the API? (+ who provides it?)
* What are the prerequisites to access the API (e.g., authentication)? 
* What does a simple API call look like? 
* How can we access the API from R (httr + other packages)? * Are there social science research examples using the API?

## Authentication
A lot of the APIs require that you authenticate with the API provider. The underlying script of this Review is written in such a way that it contains R chunks for authentication, however they will not be visible below (we only show placeholders for you to recognize at which step you will need to authenticate). These chunks in most cases make use of so-called keys in JSON format (e.g., service account key for Google APIs). However cloning the corresponding [repository]("https://github.com/paulcbauer/apis_for_social_scientists_a_review") of this Review will not result in giving you the keys, hence in order to replicate our API calls, you will have to generate and usw your own individual key.

<!--As a consequence we can not make the corresponding [github repository public](https://github.com/paulcbauer/apis_for_social_scientists_a_review).-->


## Packages
The code examples rely on different packages. It's probably easiest if you install all of them in one go. The `p_load()` function (`pacman` package) checks whether packages are installed. If not they are installed and loaded.

<!-- add all used packages -->

```{r eval=FALSE, include=TRUE}
library(pacman)
pacman::p_load(
  dplyr
)
devtools::install_github("quanteda/quanteda.corpora")
```

## Versioning
The objective is to have a document that is up to date. Hence, the versioning because it allows to produce new versions of the document in which outdated chapters are updated or excluded (e.g., if an API ceases to exist).



<!--
* Data vs. machine learning APIS
* Problem of replicability for ML APIs
-->